<?php
/**
 * @file
 * Islandora module for streaming video
 */

/**
 * Implements hook_theme().
 */
function islandora_streaming_video_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_streaming_video' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-streaming-video',
      'pattern' => 'islandora_streaming_video__',
      'variables' => array('object' => NULL),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_streaming_video_islandora_streamingVideoCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_streaming_video', array('object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_streaming_video_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_streaming_video');

  // video Content Model.
  $video_content_model = $connection->repository->constructObject('islandora:streamingVideoCModel');
  $video_content_model->owner = 'fedoraAdmin';
  $video_content_model->label = 'Islandora Video Content Model';
  $video_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $ds_composite_datastream = $video_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $ds_composite_datastream->label = 'DS-COMPOSITE-MODEL';
  $ds_composite_datastream->mimetype = 'text/xml';
  $ds_composite_datastream->setContentFromFile($module_path . "/xml/islandora_streaming_video_ds_composite_model.xml", FALSE);
  $video_content_model->ingestDatastream($ds_composite_datastream);

  /*
  // Collection.
  $entity_collection = $connection->repository->constructObject('islandora:tune_work_collection');
  $entity_collection->owner = 'fedoraAdmin';
  $entity_collection->label = 'Tune Collection';
  $entity_collection->models = 'islandora:collectionCModel';
  $entity_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // TN Datastream.
  $thumbnail_datastream = $entity_collection->constructDatastream('TN', 'M');
  $thumbnail_datastream->label = 'Thumbnail';
  $thumbnail_datastream->mimetype = 'image/png';
  $thumbnail_datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $entity_collection->ingestDatastream($thumbnail_datastream);
  // Collection policy datastream.
  $collection_policy_datastream = $entity_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $collection_policy_datastream->label = 'Collection policy';
  $collection_policy_datastream->mimetype = 'text/xml';
  $collection_policy_datastream->setContentFromFile("$module_path/xml/islandora_entity_collection_policy.xml", FALSE);
  $entity_collection->ingestDatastream($collection_policy_datastream);
  */

  return array(
    'islandora_streaming_video' => array(
      'title' => 'Islandora streaming video',
      'objects' => array(
        $video_content_model,
      ),
    ),
  );
}
